# This is a basic workflow to help you get started with Actions

name: docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, gh-pages ]
  pull_request:
    branches: [ main, gh-pages ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# A workflow run is artifactmade up of one or more jobs that can run sequentially or in parallel
jobs:
  docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocstrings[python] mkdocstrings[go] mkdocs-extra-sass-plugin "mkdocs-minify-plugin>=0.3" "mkdocs-redirects>=1.0" mike "jinja2==3.0.3" mkdocs-autorefs mkdocs-enumerate-headings-plugin
      - run: mkdocs build
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      - run: mkdir ./site/dist
      - run: cp gw* ./site/dist/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1